# Generated by Django 5.0.1 on 2024-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_timestampedmodel_rename_author_book_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
