# Generated by Django 5.0.1 on 2024-02-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_transaction_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='collection_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
