# Generated by Django 5.0.1 on 2024-02-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_transaction_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='collection_date',
            field=models.DateField(null=True),
        ),
    ]
